title: <p align="center"> Priyesh Shah </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/priyesh-shah-b8011631/">LinkedIn</a> |
  <a href="https://github.com/priyesh-shah">GitHub</a>
  
  <br>   
  As a Software Engineering Manager with 15+ years of software development experience who quickly and successfully responds to ever-changing environments and situations, consistently achieves goals within critical project deadlines and is able to leverage an eye for detail, ensures success and quality.
  My progressive background in devising and executing on strategic software engineering and project management initiatives is substantial. My confidence as leader comes from years of experience guiding, coaching, and directing technology teams.
  A true believer in Scrum/Agile/Lean methodologies, CICD, and TDD to deliver high-quality software.
  <br>
  </p>



theme: jekyll-theme-minimal